# Dispatcher implementation with FSM Storage for our bot.
# DO NOT EDIT THIS FILE.
# Written by: Daniil Ermolaev <blcklptn@icloud.com> - 17.07.2023.


from aiogram import Bot, types
from aiogram.dispatcher import Dispatcher
from aiogram.utils import executor
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.contrib.middlewares.logging import LoggingMiddleware

from core.config import settings


storage = MemoryStorage()
bot = Bot(token=settings.TOKEN)
dp = Dispatcher(bot, storage=storage)
dp.middleware.setup(LoggingMiddleware())
